// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHa3eaP50WKn12mr-qO8hxEfHBUJtSRsQ',
    appId: '1:398529024776:web:f29a7b252c27a2dd9052bd',
    messagingSenderId: '398529024776',
    projectId: 'warungkadet-577cc',
    authDomain: 'warungkadet-577cc.firebaseapp.com',
    storageBucket: 'warungkadet-577cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQwYe7RzWgqXc-8EQzekO6OKK9V2lX1U',
    appId: '1:398529024776:android:edf929667e6d8b6d9052bd',
    messagingSenderId: '398529024776',
    projectId: 'warungkadet-577cc',
    storageBucket: 'warungkadet-577cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgK36vK0522k-KMir4jSIaKhpRKeNHaHk',
    appId: '1:398529024776:ios:c358bb674a2a9cfd9052bd',
    messagingSenderId: '398529024776',
    projectId: 'warungkadet-577cc',
    storageBucket: 'warungkadet-577cc.appspot.com',
    iosClientId: '398529024776-78fqcm9aoeo9id0k0811sdjejr6d3ltu.apps.googleusercontent.com',
    iosBundleId: 'com.example.wk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgK36vK0522k-KMir4jSIaKhpRKeNHaHk',
    appId: '1:398529024776:ios:c358bb674a2a9cfd9052bd',
    messagingSenderId: '398529024776',
    projectId: 'warungkadet-577cc',
    storageBucket: 'warungkadet-577cc.appspot.com',
    iosClientId: '398529024776-78fqcm9aoeo9id0k0811sdjejr6d3ltu.apps.googleusercontent.com',
    iosBundleId: 'com.example.wk',
  );
}
